import { notFound } from "next/navigation"
import Link from "next/link"
import { ArrowUpRight, BriefcaseBusiness, ExternalLink, MapPin, Rocket, Sparkles } from "lucide-react"
import { db } from "@/lib/db"
import { publicProfilePages } from "@/lib/db/schema"
import { eq } from "drizzle-orm"

export default async function PublicBusinessPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const rows = await db.select().from(publicProfilePages).where(eq(publicProfilePages.slug, slug)).limit(1)
  const page = rows[0]
  if (!page || !page.isPublished) notFound()
  const isCompany = page.pageType === "company"
  return <main className="min-h-svh bg-background"><div className="mx-auto min-h-svh w-full max-w-3xl border-x border-border/60 bg-background"><div className="h-2 bg-gradient-to-r from-jade via-cobalt to-ruby" /><header className="relative overflow-hidden border-b border-border px-6 pb-8 pt-8 sm:px-10"><div className="absolute -right-20 -top-24 size-72 rounded-full bg-jade/15 blur-3xl" /><div className="relative"><Link href="/" className="text-sm text-muted-foreground">BR8</Link><div className="mt-12 flex items-start justify-between gap-5"><div><span className="inline-flex items-center gap-2 rounded-full bg-secondary px-3 py-1 text-xs font-semibold text-secondary-foreground">{isCompany ? <BriefcaseBusiness className="size-3.5" /> : <Rocket className="size-3.5" />}{isCompany ? "Entreprise" : "Projet"}</span><h1 className="mt-4 text-4xl font-black tracking-tight sm:text-6xl">{page.name}</h1>{page.tagline ? <p className="mt-3 max-w-xl text-lg leading-relaxed text-muted-foreground">{page.tagline}</p> : null}</div><div className="grid size-20 shrink-0 place-items-center rounded-3xl bg-primary text-2xl font-black text-primary-foreground shadow-xl">{page.name.slice(0, 2).toUpperCase()}</div></div></div></header><section className="grid gap-8 px-6 py-8 sm:grid-cols-[1fr_240px] sm:px-10"><div><p className="text-base leading-8 text-foreground">{page.description || "Une page publique BR8 pour présenter une activité, un projet et les personnes qui le font vivre."}</p>{page.highlights?.length ? <div className="mt-7 flex flex-wrap gap-2">{page.highlights.map((highlight) => <span key={highlight} className="rounded-full border border-border bg-card px-3 py-2 text-sm">{highlight}</span>)}</div> : null}</div><aside className="flex flex-col gap-3 rounded-3xl border border-border bg-card p-5"><p className="text-xs font-bold uppercase tracking-[0.18em] text-jade">À retenir</p>{page.location ? <p className="flex items-center gap-2 text-sm"><MapPin className="size-4 text-muted-foreground" />{page.location}</p> : null}{page.websiteUrl ? <a href={page.websiteUrl} target="_blank" rel="noreferrer" className="flex items-center gap-2 text-sm font-semibold text-primary">Visiter le site <ExternalLink className="size-4" /></a> : null}<Link href="/sign-up" className="mt-2 flex items-center justify-between rounded-2xl bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground">Rejoindre BR8 <ArrowUpRight className="size-4" /></Link></aside></section><footer className="border-t border-border px-6 py-5 text-xs text-muted-foreground sm:px-10"><Sparkles className="mr-1 inline size-3" />Page créée avec BR8</footer></div></main>
}
